### ISSUE TITLE
Alien::xz build blocked by xz backdoor situation

### ISSUE THREAD

**Issue by smonff** [PerlAlien/Alien-xz#8]
Not really a bug, more some kind of testimony related to the [current xz situation](https://arstechnica.com/security/2024/04/what-we-know-about-the-xz-utils-backdoor-that-almost-infected-the-world/). Hope it could help people ending up here in search of some clues and save them some time to understand the situation.

`Alien::xz` tries to download the `xz-utils` sources from `https://tukaani.org/xz/`. The redirection DNS (`https://xz.tukaani.org/xz-utils/`) has been [removed by the maintainer](https://tukaani.org/xz-backdoor/), making the download impossible, and finally failing the `Alien::xz` build process.

```
Building and testing Alien-xz-0.08 ... cp lib/Alien/xz.pm blib/lib/Alien/xz.pm
"/usr/bin/perl" -MAlien::Build::MM=cmd -e prefix site /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
main> prefix /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/auto/share/dist/Alien-xz
"/usr/bin/perl" -MAlien::Build::MM=cmd -e version 0.08
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
"/usr/bin/perl" -MAlien::Build::MM=cmd -e download
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::CommandLine
Alien::Build::Plugin::Fetch::HTTPTiny> 503 Service Unavailable fetching https://tukaani.org/xz/
error fetching https://tukaani.org/xz/: 503 Service Unavailable at /usr/local/share/perl/5.26.1/Alien/Build/Plugin/Fetch/HTTPTiny.pm line 106.
Makefile:988: recipe for target '_alien/mm/download' failed
make: *** [_alien/mm/download] Error 255
FAIL
! Installing Alien::xz failed. See /root/.cpanm/work/1712238981.20365/build.log for details. Retry with --force to force install it.
``` 

The content of the build log says:

```
error fetching https://tukaani.org/xz/: 503 Service Unavailable at /tmp/builds/local/lib/perl5/Alien/Build/Plugin/Fetch/HTTPTiny.pm line 106.
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Alien::Build::Plugin::Fetch::HTTPTiny> 503 Service Unavailable fetching https://tukaani.org/xz/
```

`xz` maintainers [said](https://tukaani.org/xz-backdoor/): 

> xz.tukaani.org DNS name (CNAME) has been removed. XZ Utils currently doesn’t have a home page. A few links on tukaani.org are still broken but many were fixed on 2024-04-04.

So it will surely be back very soon.

**Comment by Rid** [comment]
Just hit this bug when trying to build `XML::LibXML`

According to https://tukaani.org/xz-backdoor/:

>xz.tukaani.org DNS name (CNAME) has been removed and won’t be restored.
>
>The XZ projects have moved to their old URLs on tukaani.org. XZ Utils’s home page is under construction still though.

Wouldn't it be better to download the sources directly from github @plicease?

**Comment by Rid** [comment]
@plicease would it be possible to use https://github.com/PerlAlien/Alien-Build-Plugin-Download-GitHub to get the latest release from https://github.com/tukaani-project/xz?

**Comment by plicease** [comment]
> @plicease would it be possible to use https://github.com/PerlAlien/Alien-Build-Plugin-Download-GitHub to get the latest release from https://github.com/tukaani-project/xz?

Yeah that is probably the right thing to do.

**Comment by plicease** [comment]
I think something like this:

**Comment by Rid** [comment]
LGTM! Thanks for the speedy PR @plicease

**Comment by plicease** [comment]
Okay the new tarballs do not have a `configure` (probably because of the exact nature of the backdoor), so I will add a dependency on `Alien::Autotools`.

**Comment by plicease** [comment]
This should be addressed in the version headed to CPAN right now.  Unfortunately, now that we have to build `configure` we've added a dependency on `autopoint` which hasn't been alienized yet, and most people probably won't have it.  I felt that it was better to get this out than to keep it completely broken, and we can try to fix the autopoint dependency later so I will close this and open #11

**Comment by smonff** [comment]
Worked well for me, as long `autopoint` has been installed through OS packages. Thanks for the hardwork @plicease !
